### PR TITLE
Xcode 10 updates

### PR DESCRIPTION
**Pull request by jameshartt**
First commit gets us through it compiling.

Second is housekeeping and general gumpf added by Xcode from building and updating to recommended settings.

Currently used in an Xcode 10 build for the MAVIS app.

Thanks for this project, really useful to us, to allow us to run unit tests and looks at other non Metal based UI through the simulator.

### CODE REVIEW

**Comment by mats-claassen** [comment]
Thanks for the contribution! I think we should wait to merge this for when Xcode 10 (stable) is out as there might be changes.

**Review by mats-claassen — APPROVED** [review]

**Comment by jameshartt** [comment]
Of course, we have a particular sensitivity to Beta releases over here, as we need to be fully aware that nothing has messed too much with our integration with the cameras. Thanks!

**Comment by mats-claassen** [comment]
Fine, just tested on Xcode 10 and gave me no errors. Thanks @jameshartt

**Comment by jameshartt** [comment]
Excellent, thanks!

**Pull request merged**
